#!/usr/bin/env bash
# This bash script displays `To infinity and beyond` indefinitely
# Requirement: sleep 2 is in between each iteration of the loop

while true
do
	echo "To infinity and beyond"
	sleep 2
done
