#!/usr/bin/env bash
# This script displays the content of the file `/etc/passwd.
# it displays on the username, user id, and Home directory path 
# for the user.

myfile="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
