#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash
# Requirement:

# You must use the for loop only
# Do not display hidden files

mylist=$(ls)

for i in $mylist; 
do
  echo "$i" | cut -d '-' -f2
done
